# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecab53b65a634d68534b2fa50f9ae8fc68ac4c095702ea676d40a368c4f35340eb1489e1419782a718dcf4105ccc564208c3d59c061a2f4b867832e00ca33d94

test:
  secret_key_base: 7a2c1415fc3e9b62766f6b364ce0694bf929ef87109e9374c3d6d8152922e00993e796923aec1e6c113edee432d7e4e0bc1e43eb92c59ba9c0bbf0dc4c375b58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
